### ISSUE TITLE
add a confirmation screen

### ISSUE THREAD

**Issue by awebdeveloper** [0x192/Universal-Android-Debloater#305] opened 2022-07-12 12:03 UTC
Hi, Thanks a lot for this app. Could you add a confirmation screen showing which apps are getting uninstalled. I happened to accidentally delete Google Calendar today though I don't remember clicking it.

**Comment by AnonymousWP** [comment] 2022-07-12 12:11
Duplicate of https://github.com/0x192/universal-android-debloater/issues/170. [Winston said](https://github.com/0x192/universal-android-debloater/issues/170#issuecomment-1086749614) it won't come anytime soon.

**Closed as completed** 2022-07-12 12:16 UTC
