### ISSUE TITLE
Redmi note 10 not working

### ISSUE THREAD

**Issue by anirugu** [0x192/Universal-Android-Debloater#176] opened 2022-04-02 07:18 UTC
I uninstall all the package by select all and uninstall, now when I reboot the pc it's stuck on activate this device. When I enter the password it's saying RPC error.

**Comment by 0x192** [comment] 2022-04-02 23:46
>  I reboot the pc it's stuck on activate this device

You mean _reboot the phone_ right? Otherwise, it's not a issue with this software.

You at least need to give me [the log file](https://github.com/0x192/universal-android-debloater/wiki/FAQ#where-are-the-logfiles=) if you want me to help you. 

And give me the exact error message you get.

Anyway, you will have to find the faulty package(s) because you have the phone, not me. You can try by dichotomy:
1) Restore all the packages and check your issue is fixed
2) Uninstall the first half of the `Recommended` list. 
3) Check if you have the issue
4) If you have the issue, you know the culprit is in this half. Restore the packages and uninstall the half of this set. Go back to 3
If you don't have the issue, you know the culprit is in the other half. You know what to do...

Keep me informed so I can update the debloat list for everyone else :slightly_smiling_face:

**Comment by anirugu** [comment] 2022-04-03 03:41
yes, I means reboot the phone. I have attached the logs, After reading your message I tried to do use recommended (earlier I also didn't change that option, by default it's recommanded),
[UAD_20220402.log](https://github.com/0x192/universal-android-debloater/files/8403781/UAD_20220402.log)
[UAD_20220403.log](https://github.com/0x192/universal-android-debloater/files/8403782/UAD_20220403.log)
 
I have tried it 3-4 times and it's broke all the times. Let me know if I can help you further for testing it.

**Comment by 0x192** [comment] 2022-04-04 21:36
You seems to have used an old release. The latest one (`v0.5`) may have fixed your problem. Always use the latest version before reporting an issue and use the right issue template (` Debloat issue report `)

So, use the `v0.5`, restore all the packages (and check your problem is gone), and try again with the `Recommended` list.

If you still have your problem, then you'll have to do what I told you to do :

> Anyway, you will have to find the faulty package(s) **because you have the phone on hand, not me**. You can try by dichotomy:
>  - Restore all the packages and check your issue is fixed
> - Uninstall the first half of the Recommended list.
> - Check if you have the issue
> - If you have the issue, you know the culprit is in this half. Restore the packages and uninstall the half of this set. Go back to 3
> - If you don't have the issue, you know the culprit is in the other half. You know what to do...

Just to be sure, you don't have a XIaomi account bind to your phone right? As stated in the README:

> From the settings, disconnect from any OEM accounts (when you delete an OEM account package it could lock you on the lockscreen because the phone can't associate your identity anymore)

**Comment by 0x192** [comment] 2022-04-09 18:40
I think you have this problem: 

<img src="https://user-images.githubusercontent.com/55300518/162587314-86a3ec84-1edc-4df1-abf3-2c65b690a8b5.jpg" width="250" alt="uad_screenshot">

The culprit is `com.xiaomi.account`. I removed it from the `Recommended` list.

duplicate of #183

**Closed as completed by 0x192** 2022-04-09 18:40 UTC
Labels: needs more information, package::breakage

**Comment by anirugu** [comment] 2022-04-19 14:40
Yes, exactly. I was getting this error every time when I uninstall apps using UAD.
