### ISSUE TITLE
Honor smartphones doesnt support detect!

### ISSUE THREAD

**Issue by vinyashegde** [0x192/Universal-Android-Debloater#229] opened 2022-05-15 11:49 UTC
**Describe the bug**
Honor smartphones doesnt support detect!

**Expected behavior**
no detection

**You have a solution?**
What to do to fix the issue.

**Comment by 0x192** [comment] 2022-05-22 21:00
duplicate of #219

>  Upload the logfile generated by UAD. You can hardly be helped without.

:roll_eyes: 


Anyway, I'm pretty sure you didn't read the the README (which is a something you should... READ :roll_eyes: ). You need to add ADB to your PATH

> Download [android platform tools](https://dl.google.com/android/repository/platform-tools-latest-windows.zip) and unzip it somewhere. [Add the folder to your PATH](https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/).
>
> https://github.com/0x192/universal-android-debloater#how-to-use-it

**Closed as completed by 0x192** 2022-05-22 21:00 UTC
Labels: bug, duplicate, invalid

**Comment by 0x192** [comment] 2022-05-22 21:01
duplicate of #219
